//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AOC2020.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AOC2020.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1664
        ///1939
        ///1658
        ///1791
        ///1011
        ///1600
        ///1587
        ///1930
        ///1846
        ///1955
        ///1885
        ///1793
        ///1876
        ///1905
        ///1997
        ///1900
        ///1956
        ///1981
        ///1890
        ///1612
        ///638
        ///1897
        ///1888
        ///1742
        ///1613
        ///1982
        ///1932
        ///1923
        ///1065
        ///1827
        ///1919
        ///1236
        ///1195
        ///1917
        ///1990
        ///1764
        ///1902
        ///1911
        ///1999
        ///1906
        ///1817
        ///1841
        ///368
        ///747
        ///1881
        ///1941
        ///1894
        ///1898
        ///1887
        ///1958
        ///1862
        ///1940
        ///1819
        ///1873
        ///1959
        ///1977
        ///1301
        ///1945
        ///1961
        ///1673
        ///1879
        ///1889
        ///1872
        ///155
        ///1718
        ///1637
        ///1899
        ///1988
        ///1720
        ///1856
        ///1816
        ///1866
        ///1963
        ///1880
        ///1884
        ///1970
        ///1985
        ///1869
        ///1686
        ///1832
        ///1697
        ///1381
        ///1585
        ///1993
        ///2000
        ///587
        ///1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day1 {
            get {
                return ResourceManager.GetString("Day1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1-5 k: kkkkhkkkkkkkkkk
        ///5-7 k: blkqhtxfgktdkxzkksk
        ///15-16 x: xxxxxxxxxxxxxxlf
        ///3-5 j: fjpvj
        ///17-20 x: zsxjrxkgxxxxxxxmxgxf
        ///5-6 m: swjzmmmlx
        ///2-4 v: vqdn
        ///8-12 t: thllsbqtgdsf
        ///10-17 h: vpbrjcbhnwqhhphxjk
        ///8-9 p: zpwpppkqbpkpppp
        ///5-6 t: wtxxts
        ///3-8 v: vfsvhgvvhh
        ///1-3 v: kvvvm
        ///8-16 w: bwkqpdgwrbwjxrtqlwbw
        ///3-8 s: sssssssbs
        ///6-9 w: wwwwwcwwww
        ///5-10 r: rvwrrlxbrjhp
        ///1-4 r: rbnlkkrjphnnxpw
        ///7-9 r: zxhrpmsrrxrlr
        ///2-3 w: dwcvwb
        ///2-4 v: vlvvvv
        ///3-12 h: hbvdhhhhhqhhlzhs
        ///8-10 t: tbgfvwbtvbnghfbhxz
        ///4-8 m: dmvgkltn [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day2 {
            get {
                return ResourceManager.GetString("Day2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .......#................#......
        ///...#.#.....#.##.....#..#.......
        ///..#..#.#......#.#.#............
        ///....#...#...##.....#..#.....#..
        ///....#.......#.##......#...#..#.
        ///...............#.#.#.....#..#..
        ///...##...#...#..##.###...##.....
        ///##..#.#...##.....#.#..........#
        ///.#....#..#..#......#....#....#.
        ///...........................#...
        ///..........#.......#..#.....#.#.
        ///..#.......###..#.#.......#.#...
        ///....#..#....#....#..........#..
        ///..##..#.......#.#...#..........
        ///.....#.......#.....#....#......
        ///..........##..#.. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day3 {
            get {
                return ResourceManager.GetString("Day3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eyr:2027
        ///hcl:#602927
        ///hgt:186cm byr:1939 iyr:2019 pid:552194973 ecl:hzl
        ///
        ///pid:657988073 eyr:2020 byr:1996
        ///ecl:brn
        ///hcl:#866857 iyr:2015
        ///hgt:164cm
        ///
        ///hcl:#fffffd
        ///byr:1951 cid:321 iyr:2017 eyr:2022 ecl:brn hgt:62in pid:#6ef4e1
        ///
        ///eyr:2025 iyr:2011
        ///byr:1980
        ///hcl:#fffffd cid:129 pid:420023864
        ///hgt:150cm
        ///ecl:brn
        ///
        ///eyr:2029
        ///hcl:#ceb3a1 hgt:187cm
        ///byr:1925 ecl:amb pid:223151011 iyr:2016
        ///
        ///hcl:#cfa07d ecl:brn eyr:2022 pid:135392110 iyr:2010
        ///hgt:190cm
        ///byr:1959
        ///
        ///eyr:2024 cid:225 iyr:2018
        ///pid:522856696  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day4 {
            get {
                return ResourceManager.GetString("Day4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FBFBFBFRRL
        ///BFBBFFFRRL
        ///FFBFFFFRLL
        ///BFFFBBBRLL
        ///BBFFBFBLLR
        ///FFFFBBBRLR
        ///FBBBBFFLRR
        ///FBFFFBFRLL
        ///FFFFBFFRRR
        ///FFFBBFFRLR
        ///BFBBBBFRLL
        ///FBBFBFFLLL
        ///FFFBFFBRRL
        ///BFBFFBBLLL
        ///FFBBFBBLLR
        ///FFBFFBBRRL
        ///BFBFBBBRRL
        ///FFBFFBBLLL
        ///BFFFBBBLRR
        ///BFBFFBFRRR
        ///BFFBFFBRRL
        ///BFBFFFFLLR
        ///FFFFBBBLRR
        ///FFBBFBFRRR
        ///BFFFBFBLLL
        ///FBFFBBBRRL
        ///FBBBBBBRRL
        ///BBFBFFBLLL
        ///BFFBFFFLLL
        ///FBFFBBFLLR
        ///FBFBFFBLRL
        ///FFBFFFBRLR
        ///FFBBBBFRLL
        ///FBFBFFFLRL
        ///FBBFBBFRLR
        ///FFBBBBBLLL
        ///FBFFBFBLLL
        ///FBFFFBBRRR
        ///BBFFBBFRRR
        ///FBFFBFBRLL
        ///FBBBFBBRRR
        ///BFFFBFFRRL
        ///FFBFBFBL [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day5 {
            get {
                return ResourceManager.GetString("Day5", resourceCulture);
            }
        }
    }
}
