//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AOC2020.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AOC2020.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1664
        ///1939
        ///1658
        ///1791
        ///1011
        ///1600
        ///1587
        ///1930
        ///1846
        ///1955
        ///1885
        ///1793
        ///1876
        ///1905
        ///1997
        ///1900
        ///1956
        ///1981
        ///1890
        ///1612
        ///638
        ///1897
        ///1888
        ///1742
        ///1613
        ///1982
        ///1932
        ///1923
        ///1065
        ///1827
        ///1919
        ///1236
        ///1195
        ///1917
        ///1990
        ///1764
        ///1902
        ///1911
        ///1999
        ///1906
        ///1817
        ///1841
        ///368
        ///747
        ///1881
        ///1941
        ///1894
        ///1898
        ///1887
        ///1958
        ///1862
        ///1940
        ///1819
        ///1873
        ///1959
        ///1977
        ///1301
        ///1945
        ///1961
        ///1673
        ///1879
        ///1889
        ///1872
        ///155
        ///1718
        ///1637
        ///1899
        ///1988
        ///1720
        ///1856
        ///1816
        ///1866
        ///1963
        ///1880
        ///1884
        ///1970
        ///1985
        ///1869
        ///1686
        ///1832
        ///1697
        ///1381
        ///1585
        ///1993
        ///2000
        ///587
        ///1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day1 {
            get {
                return ResourceManager.GetString("Day1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 71
        ///183
        ///111
        ///89
        ///92
        ///142
        ///25
        ///101
        ///52
        ///86
        ///18
        ///22
        ///70
        ///2
        ///135
        ///163
        ///34
        ///143
        ///153
        ///35
        ///144
        ///24
        ///23
        ///94
        ///100
        ///102
        ///17
        ///57
        ///76
        ///182
        ///134
        ///38
        ///7
        ///103
        ///66
        ///31
        ///11
        ///121
        ///77
        ///113
        ///128
        ///82
        ///99
        ///148
        ///137
        ///41
        ///32
        ///48
        ///131
        ///60
        ///127
        ///138
        ///73
        ///28
        ///10
        ///84
        ///180
        ///63
        ///125
        ///53
        ///176
        ///165
        ///114
        ///145
        ///152
        ///72
        ///107
        ///167
        ///59
        ///164
        ///78
        ///126
        ///118
        ///136
        ///83
        ///79
        ///58
        ///14
        ///106
        ///69
        ///51
        ///39
        ///157
        ///42
        ///177
        ///173
        ///93
        ///141
        ///3
        ///33
        ///13
        ///19
        ///45
        ///154
        ///95
        ///170
        ///54
        ///181
        ///6
        ///151
        ///1
        ///112
        ///96
        ///115
        ///85
        ///108
        ///166
        ///160
        ///40
        ///122
        ///12.
        /// </summary>
        internal static string Day10 {
            get {
                return ResourceManager.GetString("Day10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16
        ///10
        ///15
        ///5
        ///1
        ///11
        ///7
        ///19
        ///6
        ///12
        ///4.
        /// </summary>
        internal static string Day10Test {
            get {
                return ResourceManager.GetString("Day10Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LLLLLL.LL.LLLLLL.LLLLLLL.LLLLLL.LLLLL.LLLLLLLLLLLLLLLLLL.LLLL.L.LLL.LLLLLLLL.LLLLLLLL.LLLLL
        ///LLLLLL.L.LL.LLLL.L.LLLL.LLLLLLL.LLLLL.LLLLLLLL.LLLLLL.LLLLLLL.LLLLLLLLLLLLLL.LLLLLLLL.LLLLL
        ///LLLLLL.LLLL.LLLL.LLLLLLLLLLLLLL.LLLLL.LLLL.LLLLLLLLLLL.L.LLLL.LLLLL.LLL..LLL.LLLLLLLLLLLLLL
        ///LLLLLL.LLLL.LLLLLLLLLL.L.LLLLLLLLLLLLLLLLLLL.L.LLLLLLL.L.L.LL.LLLLL..LLLLLLL.LLLLLLLL.LL.LL
        ///LLLLLL.LLLL.LLLL.LLLLLLLLLLLLL..LLLLLLLLLLLLLL.LLLL.LL.LLLLLL.LLLLL.LLL.LLLL.LLLLLLLL.LLLLL
        ///LLLL.L.LLLLLLLLLLLLLLLLLLLLLLLL.LLLLL.LLLLLLLL. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day11 {
            get {
                return ResourceManager.GetString("Day11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L.LL.LL.LL
        ///LLLLLLL.LL
        ///L.L.L..L..
        ///LLLL.LL.LL
        ///L.LL.LL.LL
        ///L.LLLLL.LL
        ///..L.L.....
        ///LLLLLLLLLL
        ///L.LLLLLL.L
        ///L.LLLLL.LL.
        /// </summary>
        internal static string Day11Test {
            get {
                return ResourceManager.GetString("Day11Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1-5 k: kkkkhkkkkkkkkkk
        ///5-7 k: blkqhtxfgktdkxzkksk
        ///15-16 x: xxxxxxxxxxxxxxlf
        ///3-5 j: fjpvj
        ///17-20 x: zsxjrxkgxxxxxxxmxgxf
        ///5-6 m: swjzmmmlx
        ///2-4 v: vqdn
        ///8-12 t: thllsbqtgdsf
        ///10-17 h: vpbrjcbhnwqhhphxjk
        ///8-9 p: zpwpppkqbpkpppp
        ///5-6 t: wtxxts
        ///3-8 v: vfsvhgvvhh
        ///1-3 v: kvvvm
        ///8-16 w: bwkqpdgwrbwjxrtqlwbw
        ///3-8 s: sssssssbs
        ///6-9 w: wwwwwcwwww
        ///5-10 r: rvwrrlxbrjhp
        ///1-4 r: rbnlkkrjphnnxpw
        ///7-9 r: zxhrpmsrrxrlr
        ///2-3 w: dwcvwb
        ///2-4 v: vlvvvv
        ///3-12 h: hbvdhhhhhqhhlzhs
        ///8-10 t: tbgfvwbtvbnghfbhxz
        ///4-8 m: dmvgkltn [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day2 {
            get {
                return ResourceManager.GetString("Day2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .......#................#......
        ///...#.#.....#.##.....#..#.......
        ///..#..#.#......#.#.#............
        ///....#...#...##.....#..#.....#..
        ///....#.......#.##......#...#..#.
        ///...............#.#.#.....#..#..
        ///...##...#...#..##.###...##.....
        ///##..#.#...##.....#.#..........#
        ///.#....#..#..#......#....#....#.
        ///...........................#...
        ///..........#.......#..#.....#.#.
        ///..#.......###..#.#.......#.#...
        ///....#..#....#....#..........#..
        ///..##..#.......#.#...#..........
        ///.....#.......#.....#....#......
        ///..........##..#.. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day3 {
            get {
                return ResourceManager.GetString("Day3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eyr:2027
        ///hcl:#602927
        ///hgt:186cm byr:1939 iyr:2019 pid:552194973 ecl:hzl
        ///
        ///pid:657988073 eyr:2020 byr:1996
        ///ecl:brn
        ///hcl:#866857 iyr:2015
        ///hgt:164cm
        ///
        ///hcl:#fffffd
        ///byr:1951 cid:321 iyr:2017 eyr:2022 ecl:brn hgt:62in pid:#6ef4e1
        ///
        ///eyr:2025 iyr:2011
        ///byr:1980
        ///hcl:#fffffd cid:129 pid:420023864
        ///hgt:150cm
        ///ecl:brn
        ///
        ///eyr:2029
        ///hcl:#ceb3a1 hgt:187cm
        ///byr:1925 ecl:amb pid:223151011 iyr:2016
        ///
        ///hcl:#cfa07d ecl:brn eyr:2022 pid:135392110 iyr:2010
        ///hgt:190cm
        ///byr:1959
        ///
        ///eyr:2024 cid:225 iyr:2018
        ///pid:522856696  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day4 {
            get {
                return ResourceManager.GetString("Day4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FBFBFBFRRL
        ///BFBBFFFRRL
        ///FFBFFFFRLL
        ///BFFFBBBRLL
        ///BBFFBFBLLR
        ///FFFFBBBRLR
        ///FBBBBFFLRR
        ///FBFFFBFRLL
        ///FFFFBFFRRR
        ///FFFBBFFRLR
        ///BFBBBBFRLL
        ///FBBFBFFLLL
        ///FFFBFFBRRL
        ///BFBFFBBLLL
        ///FFBBFBBLLR
        ///FFBFFBBRRL
        ///BFBFBBBRRL
        ///FFBFFBBLLL
        ///BFFFBBBLRR
        ///BFBFFBFRRR
        ///BFFBFFBRRL
        ///BFBFFFFLLR
        ///FFFFBBBLRR
        ///FFBBFBFRRR
        ///BFFFBFBLLL
        ///FBFFBBBRRL
        ///FBBBBBBRRL
        ///BBFBFFBLLL
        ///BFFBFFFLLL
        ///FBFFBBFLLR
        ///FBFBFFBLRL
        ///FFBFFFBRLR
        ///FFBBBBFRLL
        ///FBFBFFFLRL
        ///FBBFBBFRLR
        ///FFBBBBBLLL
        ///FBFFBFBLLL
        ///FBFFFBBRRR
        ///BBFFBBFRRR
        ///FBFFBFBRLL
        ///FBBBFBBRRR
        ///BFFFBFFRRL
        ///FFBFBFBL [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day5 {
            get {
                return ResourceManager.GetString("Day5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jmqnkzlsfedaptx
        ///usjfkadqwmeyilph
        ///
        ///lodbmhvcaset
        ///wcognbeaxhmvdt
        ///
        ///f
        ///f
        ///f
        ///f
        ///
        ///dwxfircztpyshol
        ///dogfryaxtlhzscw
        ///gwchdzyftolsxra
        ///thrdwcxfosqzyl
        ///rholzdwctxfsy
        ///
        ///dbifho
        ///zmdh
        ///hobd
        ///
        ///iqjdvpxyfremnbzuohglc
        ///dpohfyzjqicbnegrmuxvl
        ///uromlgbqyjznecvpxhidf
        ///cyebghlzpoiqmrjfxnudv
        ///vjgzlpbfondxrceyhqimu
        ///
        ///mpxsao
        ///oxasmp
        ///rzxqokamp
        ///
        ///bigjutwl
        ///
        ///rdcwfenzhlos
        ///gzorslxh
        ///marjhzqbipoukvls
        ///
        ///fdclagjkvrmwxqyszupnoethbi
        ///zdiyfcuahnkxewltsgqrpbj
        ///derbpujchxlqfngtaskzwyi
        ///
        ///gyx
        ///yg
        ///gx
        ///fgver
        ///
        ///nb
        ///bo
        ///
        ///efruscbgi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day6 {
            get {
                return ResourceManager.GetString("Day6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dim silver bags contain 3 posh fuchsia bags.
        ///wavy olive bags contain 1 striped olive bag, 1 dull cyan bag.
        ///dull coral bags contain 1 dim olive bag, 5 muted violet bags, 2 dark gray bags.
        ///bright olive bags contain 3 light indigo bags, 3 dark coral bags.
        ///clear lavender bags contain 1 dark olive bag.
        ///dim lime bags contain 3 dotted red bags.
        ///drab indigo bags contain 5 striped coral bags, 2 muted bronze bags.
        ///striped orange bags contain 5 wavy fuchsia bags, 5 clear red bags, 3 plaid red bags.
        ///dotted indi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day7 {
            get {
                return ResourceManager.GetString("Day7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jmp +248
        ///acc +11
        ///acc +50
        ///acc +44
        ///jmp +531
        ///acc -17
        ///jmp +572
        ///acc +19
        ///acc +9
        ///jmp +221
        ///nop +373
        ///acc +7
        ///jmp +502
        ///acc +39
        ///jmp +12
        ///acc +7
        ///nop +482
        ///jmp +144
        ///acc -4
        ///jmp +85
        ///acc +12
        ///nop +446
        ///nop +162
        ///jmp +270
        ///acc -19
        ///jmp +402
        ///acc +8
        ///acc +28
        ///acc -13
        ///acc +30
        ///jmp +81
        ///acc -15
        ///jmp +20
        ///acc +28
        ///jmp -19
        ///nop +190
        ///acc +2
        ///jmp +61
        ///nop +237
        ///jmp +421
        ///acc +24
        ///jmp +221
        ///acc +1
        ///jmp +1
        ///jmp +265
        ///nop +94
        ///jmp +1
        ///jmp +370
        ///acc +19
        ///nop +39
        ///jmp +454
        ///jmp +162
        ///jmp +196
        ///jmp +7
        ///acc +37
        ///acc +1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day8 {
            get {
                return ResourceManager.GetString("Day8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 33
        ///38
        ///29
        ///45
        ///26
        ///35
        ///14
        ///5
        ///27
        ///44
        ///18
        ///8
        ///7
        ///23
        ///16
        ///10
        ///41
        ///21
        ///9
        ///30
        ///17
        ///42
        ///25
        ///31
        ///20
        ///12
        ///59
        ///13
        ///22
        ///40
        ///15
        ///47
        ///14
        ///33
        ///26
        ///19
        ///24
        ///49
        ///27
        ///28
        ///23
        ///29
        ///32
        ///21
        ///34
        ///30
        ///35
        ///36
        ///48
        ///55
        ///50
        ///37
        ///58
        ///38
        ///39
        ///43
        ///41
        ///45
        ///40
        ///98
        ///78
        ///57
        ///79
        ///44
        ///49
        ///51
        ///71
        ///106
        ///87
        ///66
        ///65
        ///72
        ///73
        ///124
        ///113
        ///75
        ///118
        ///77
        ///80
        ///81
        ///83
        ///130
        ///138
        ///84
        ///122
        ///117
        ///101
        ///93
        ///110
        ///147
        ///126
        ///150
        ///148
        ///190
        ///159
        ///137
        ///145
        ///152
        ///340
        ///194
        ///273
        ///157
        ///158
        ///176
        ///184
        ///177
        ///296
        ///185
        ///286
        ///203
        ///310
        ///211
        ///269
        ///247
        ///263
        ///271
        ///477
        ///282
        ///289
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day9 {
            get {
                return ResourceManager.GetString("Day9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 35
        ///20
        ///15
        ///25
        ///47
        ///40
        ///62
        ///55
        ///65
        ///95
        ///102
        ///117
        ///150
        ///182
        ///127
        ///219
        ///299
        ///277
        ///309
        ///576.
        /// </summary>
        internal static string Day9Test {
            get {
                return ResourceManager.GetString("Day9Test", resourceCulture);
            }
        }
    }
}
